### ISSUE TITLE
HTF004S - Install Questions

### ISSUE THREAD

**Issue by ERisEPR** [ouaibe/dreo-cloudcutter#4]
Purchased a HTF004S - total noob with ESP Home.   After making the yaml and changing the blocks to reference my personal information, I am now stuck here "Install -> Manual download -> Beken OTA Image". The integration in HA seems to take me down this path "+ New Device --> "Name" --> "Skip This Step" --> Select device type --> BK72xx --> etc."  Is this the correct action or am i not in the correct place to see "Install -> Manual download -> Beken OTA Image"?

**Comment by ERisEPR** [comment]
OK - figured it out - in my case i had to reinstall ESPhome, the initial install of the device was giving me an error of: "MissingPackageManifestError: Could not find one of 'package.json'".  Deleted ESPHome and the ESPHome folder - reinstalled and everything went great!  Thank you for this!

One thing I am puzzeled by, I would like to read the temperature in F rather than C.  Here is the sensor:

```
sensor:
  - platform: template
    id: "temp_fan"
    filters:
      - lambda: return (x - 32.0) * (5.0/9.0); # Convert F value to C
    unit_of_measurement: "°C"
    name: "Air Temperature"
```
What lines do i comment out/get rid of to report in F, and then how do I re-flash to the fan since it is now an ESPHome device?

**Comment by ouaibe** [comment]
Your 1st question was more related to ESPHome. Glad you found a way to solve this.
Regarding your 2nd question, I'm not 100% positive on how to do it, but it shouldn't be too hard since the temperature comes directly as a hex value in F.
You probably can simply remove the "filters:" (and its lambda) element and change `unit_of_measurement` to "°F".

Let me know how it goes.

**Comment by ERisEPR** [comment]
Editied yaml to 

```
sensor:
  - platform: template
    id: "temp_fan"
    unit_of_measurement: "°F"
    name: "Air Temperature"
```

saved and installed with wireless method and everything is good!

Thank you for you work and your help!
